### PR TITLE
Fix shell completion

### LINKED ISSUE #154: Shell completion does not work properly
**Describe the bug**
Debug output is mistakenly shown in the shell completion choices:
```
$ ./ketall <TAB>
completion   -- generate the autocompletion script for the specified shell
help         -- Help about any command
version      -- Print the version information
:4           Completion ended with directive: ShellCompDirectiveNoFileComp
```
The problem is that Cobra's shell completion sends debug printouts to stderr but ketall redirects it to stdout.

**To Reproduce**
Steps to reproduce the behaviour:
```
make dev
source <(./ketall completion zsh)
compdef _ketall ketall
./ketall <TAB>
```
**Expected behavior**
Debug message should not be shown during shell completion

I will be posting a PR soon.

### PR DESCRIPTION
**Pull request by marckhouzam**
Fixes #154

This PR redirects errors to stderr because the shell completion provided by Cobra (specifically the `__complete` command) needs it.

**Before the fix**
```
$ ./ketall <TAB>
completion   -- generate the autocompletion script for the specified shell
help         -- Help about any command
version      -- Print the version information
:4           Completion ended with directive: ShellCompDirectiveNoFileComp
```
**After the fix**
```
$ ./ketall <TAB>
completion   -- generate the autocompletion script for the specified shell
help         -- Help about any command
version      -- Print the version information
```
**To reproduce the problem:**
```
make dev
source <(./ketall completion zsh)
compdef _ketall ketall
./ketall <TAB>
```

### CODE REVIEW

File: cmd/root.go [hunk 1]
```diff
@@ -74,6 +74,13 @@ var rootCmd = &cobra.Command{
 	Run: func(cmd *cobra.Command, args []string) {
 		ketall.KetAll(ketallOptions)
 	},
+	PersistentPreRun: func(cmd *cobra.Command, args []string) {
+		// For Cobra's internal `__complete` command, errors must go to stderr.
+		// This command is used for command completion and sends debug messages on stderr.
+		if cmd.Name() == cobra.ShellCompRequestCmd {
+			cmd.Root().SetErr(ketallOptions.Streams.ErrOut)
```
Comment (corneliusweig) [inline cmd/root.go:81]: I think we should set it unconditionally in `Execute` below. Or do you think this could mess up something?

**Review by corneliusweig — APPROVED** [review]
Thank you, Mark, for bringing this to Cobra and then taking care of small projects like this!

Your change lgtm, but maybe it can be set unconditionally? WDYT?

File: cmd/root.go (hunk 1 above)
Comment (marckhouzam) [reply cmd/root.go:81]: Yes that would be simpler.  I just didn't know if you had set things towards stdout for some other reason.  I'll update the PR.  Thanks for the quick review!

> Thank you, Marc, for bringing this to Cobra and then taking care of small projects like this!

I enjoyed seeing that you had gotten rid of your own `completion` command and started to use Cobra's.  It always feels good to see people benefitting. 👍

**Comment by marckhouzam** [comment]
> Thank you, Marc, for bringing this to Cobra and then taking care of small projects like this!

Oh and of course, thank you for this great plugin.  I've been using for a couple years!

**Comment by corneliusweig** [comment]
Awesome! Thank you!
This would have been hard to track down for me.
